name: Manual Workflow Trigger

on:  workflow_dispatch
    inputs:
      environment:
        description: "Choose an environment (dev, staging, production)"
        required: true
        default: "dev"
      version:
        description: "Deployment Version"
        required: false
        default: "latest"
      debug_mode:
        description: "Enable Debug Mode (true/false)"
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Print Input Values
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          echo "Debug Mode: ${{ github.event.inputs.debug_mode }}"
