name: Example Workflow

on: push

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use `echo` with inputs
        run: echo "Hello, ${{ inputs.name }}!"
        with:
          name: "DevOps Engineer"
